### ISSUE TITLE
MiitHelper里面的OnSupport方法中supplier返回为null

### ISSUE THREAD

**Issue by Florian-31** [haoguibao/OaidDemo#1]
请问一下，MiitHelper里面的OnSupport方法中supplier返回为null是什么原因呢？是supplierconfig.json文件中的appid不对，还是权限没获取到呢？

**Comment by haoguibao** [comment]
> 请问一下，MiitHelper里面的OnSupport方法中supplier返回为null是什么原因呢？是supplierconfig.json文件中的appid不对，还是权限没获取到呢？

跟appid没有关系，单纯获取oaid的话，我看也没有用到权限啊。现在按照新的sdk接入了一下，你可以试一下还有这个问题没
